ejercicio1:
	swipl -s ejercicio1.pl -g ejercicio1 -t halt

ejercicio2:
	swipl -s ejercicio2.pl -g ejercicio2 -t halt

ejercicio3:
	swipl -s ejercicio3.pl -g ejercicio3 -t halt

ejercicio4:
	swipl -s ejercicio4.pl -g ejercicio4 -t halt

ejercicio5:
	swipl -s ejercicio5.pl -g ejercicio5 -t halt

ejercicio6:
	swipl -s ejercicio6.pl -g ejercicio6 -t halt

ejercicio7:
	swipl -s ejercicio7.pl -g ejercicio7 -t halt

ejercicio8:
	swipl -s ejercicio8.pl -g ejercicio8 -t halt

ejercicio9:
	swipl -s ejercicio9.pl -g ejercicio9 -t halt

ejercicio10:
	swipl -s ejercicio10.pl -g ejercicio10 -t halt

ejercicio11:
	swipl -s ejercicio11.pl -g ejercicio11 -t halt

ejercicio12:
	swipl -s ejercicio12.pl -g ejercicio12 -t halt

ejercicio13:
	swipl -s ejercicio13.pl -g ejercicio13 -t halt

ejercicio14:
	swipl -s ejercicio14.pl -g ejercicio14 -t halt

ejercicio15:
	swipl -s ejercicio15.pl -g ejercicio15 -t halt

ejercicio16:
	swipl -s ejercicio16.pl -g ejercicio16 -t halt

ejercicio17:
	swipl -s ejercicio17.pl -g ejercicio17 -t halt

ejercicio18:
	swipl -s ejercicio18.pl -g ejercicio18 -t halt

ejercicio19:
	swipl -s ejercicio19.pl -g ejercicio19 -t halt

ejercicio20:
	swipl -s ejercicio20.pl -g ejercicio20 -t halt

ejercicio21:
	swipl -s ejercicio21.pl -g ejercicio21 -t halt

ejercicio22:
	swipl -s ejercicio22.pl -g ejercicio22 -t halt

ejercicio23:
	swipl -s ejercicio23.pl -g ejercicio23 -t halt

ejercicio24:
	swipl -s ejercicio24.pl -g ejercicio24 -t halt

ejercicio25:
	swipl -s ejercicio25.pl -g ejercicio25 -t halt

ejercicio26:
	swipl -s ejercicio26.pl -g ejercicio26 -t halt

ejercicio27:
	swipl -s ejercicio27.pl -g ejercicio27 -t halt

ejercicio28:
	swipl -s ejercicio28.pl -g ejercicio28 -t halt

ejercicio29:
	swipl -s ejercicio29.pl -g ejercicio29 -t halt

ejercicio30:
	swipl -s ejercicio30.pl -g ejercicio30 -t halt

ejercicio31:
	swipl -s ejercicio31.pl -g ejercicio31 -t halt

ejercicio32:
	swipl -s ejercicio32.pl -g ejercicio32 -t halt

ejercicio33:
	swipl -s ejercicio33.pl -g ejercicio33 -t halt

ejercicio34:
	swipl -s ejercicio34.pl -g ejercicio34 -t halt

ejercicio35:
	swipl -s ejercicio35.pl -g ejercicio35 -t halt

ejercicio36:
	swipl -s ejercicio36.pl -g ejercicio36 -t halt

ejercicio37:
	swipl -s ejercicio37.pl -g ejercicio37 -t halt

ejercicio38:
	swipl -s ejercicio38.pl -g ejercicio38 -t halt

ejercicio39:
	swipl -s ejercicio39.pl -g ejercicio39 -t halt

ejercicio40:
	swipl -s ejercicio40.pl -g ejercicio40 -t halt

ejercicio41:
	swipl -s ejercicio41.pl -g ejercicio41 -t halt

ejercicio42:
	swipl -s ejercicio42.pl -g ejercicio42 -t halt

ejercicio43:
	swipl -s ejercicio43.pl -g ejercicio43 -t halt

ejercicio44:
	swipl -s ejercicio44.pl -g ejercicio44 -t halt

ejercicio45:
	swipl -s ejercicio45.pl -g ejercicio45 -t halt

ejercicio46:
	swipl -s ejercicio46.pl -g ejercicio46 -t halt

ejercicio47:
	swipl -s ejercicio47.pl -g ejercicio47 -t halt

ejercicio48:
	swipl -s ejercicio48.pl -g ejercicio48 -t halt

ejercicio49:
	swipl -s ejercicio49.pl -g ejercicio49 -t halt

ejercicio50:
	swipl -s ejercicio50.pl -g ejercicio50 -t halt

all: $(foreach n,1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50,ejercicio$n)

clean:
	rm -f *.tmp
