# Makefile para ejecutar los programas Prolog

# Reglas para ejecutar cada ejercicio individualmente
ejercicio1:
	swipl -s ejercicio1.pl -g ejercicio1 -t halt

ejercicio2:
	swipl -s ejercicio2.pl -g ejercicio2 -t halt

ejercicio3:
	swipl -s ejercicio3.pl -g ejercicio3 -t halt

ejercicio4:
	swipl -s ejercicio4.pl -g ejercicio4 -t halt

ejercicio5:
	swipl -s ejercicio5.pl -g ejercicio5 -t halt

ejercicio6:
	swipl -s ejercicio6.pl -g ejercicio6 -t halt

ejercicio7:
	swipl -s ejercicio7.pl -g ejercicio7 -t halt

ejercicio8:
	swipl -s ejercicio8.pl -g ejercicio8 -t halt

ejercicio9:
	swipl -s ejercicio9.pl -g ejercicio9 -t halt

ejercicio10:
	swipl -s ejercicio10.pl -g ejercicio10 -t halt

ejercicio11:
	swipl -s ejercicio11.pl -g ejercicio11 -t halt

ejercicio12:
	swipl -s ejercicio12.pl -g ejercicio12 -t halt

ejercicio13:
	swipl -s ejercicio13.pl -g ejercicio13 -t halt

ejercicio14:
	swipl -s ejercicio14.pl -g ejercicio14 -t halt

ejercicio15:
	swipl -s ejercicio15.pl -g ejercicio15 -t halt

ejercicio16:
	swipl -s ejercicio16.pl -g ejercicio16 -t halt

ejercicio17:
	swipl -s ejercicio17.pl -g ejercicio17 -t halt

ejercicio18:
	swipl -s ejercicio18.pl -g ejercicio18 -t halt

ejercicio19:
	swipl -s ejercicio19.pl -g ejercicio19 -t halt

ejercicio20:
	swipl -s ejercicio20.pl -g ejercicio20 -t halt

ejercicio21:
	swipl -s ejercicio21.pl -g ejercicio21 -t halt

ejercicio22:
	swipl -s ejercicio22.pl -g ejercicio22 -t halt

ejercicio23:
	swipl -s ejercicio23.pl -g ejercicio23 -t halt

ejercicio24:
	swipl -s ejercicio24.pl -g ejercicio24 -t halt

ejercicio25:
	swipl -s ejercicio25.pl -g ejercicio25 -t halt

ejercicio26:
	swipl -s ejercicio26.pl -g ejercicio26 -t halt

ejercicio27:
	swipl -s ejercicio27.pl -g ejercicio27 -t halt

ejercicio28:
	swipl -s ejercicio28.pl -g ejercicio28 -t halt

ejercicio29:
	swipl -s ejercicio29.pl -g ejercicio29 -t halt

ejercicio30:
	swipl -s ejercicio30.pl -g ejercicio30 -t halt

# Meta para ejecutar todos los ejercicios
all: $(foreach n,1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30,ejercicio$(n))

# Meta para limpiar (en caso de necesitar eliminar archivos generados)
clean:
	rm -f *.tmp
